[colors]
; To change color scheme, change the value inside ${color-scheme.colorXX}.
; The following color schemes can be used:
; 1. Dracula
; 2. 

background = ${Dracula.background}
foreground = ${Dracula.foreground}
color0     = ${Dracula.color0}
color1	   = ${Dracula.color1}
color2     = ${Dracula.color2}
color3     = ${Dracula.color3}
color4     = ${Dracula.color4}
color5     = ${Dracula.color5}
color6     = ${Dracula.color6}
color7     = ${Dracula.color7}
color8     = ${Dracula.color8}
color9     = ${Dracula.color9}
color10    = ${Dracula.color10}
color11    = ${Dracula.color11}
color12    = ${Dracula.color12}
color13    = ${Dracula.color13}
color14    = ${Dracula.color14}
color15    = ${Dracula.color15}
alert      = ${Dracula.color1}

[Dracula]
background = #282a36
foreground = #f8f8f2
color0     = #000000 
color1     = #ff5555 
color2     = #50fa7b 
color3     = #f1fa8c 
color4     = #bd93f9 
color5     = #ff79c6 
color6     = #8be9fd 
color7     = #bfbfbf 
color8     = #4d4d4d 
color9     = #ff6e67
color10    = #5af78e 
color11    = #f4f99d 
color12    = #caa9fa 
color13    = #ff92d0 
color14    = #9aedfe 
color15    = #e6e6e6 
